- name: Instal, start and deploy apache 
  hosts: apache 
  become: yes 

  tasks:
    - name: Installing the apache
      dnf:
        name: httpd
        state: present
    - name: Start the apache
      service:
        name: httpd
        state: started
    - name: Deploy the static page
      copy:
        src: /home/ec2-user/practise/index.html
        dest: /var/www/html/
